image: 172.16.1.99/frontend/warpstor/build/warpstor-ci:chrome
before_script:

stages:
  - test
  - build

build-prod:
  stage: test
  script:
    - echo "build-prod started"
    - cd /managability/warpstor-frontend
    - cp -r /usr/src/app/node_modules /managability/warpstor-frontend/node_modules
    - npm run build:prod
  only:
    - dev
    - /.*_\d{10}$/
  tags:
    - k8s

unit-test:
  stage: test
  script:
    - echo "unit-test started"
    - cd /managability/warpstor-frontend
    - cp -r /usr/src/app/node_modules /managability/warpstor-frontend/node_modules
    - npm run test:single
  only:
    - dev
    - /.*_\d{10}$/
  tags:
    - k8s

postcommit:
  stage: build
  script:
    - echo "build-prod started"
    - cd /managability/warpstor-frontend
    - cp -r /usr/src/app/node_modules /managability/warpstor-frontend/node_modules
    - npm run build:prod
    - if [ $CI_COMMIT_REF_NAME == "master" ]; then
    -   "curl -Lvk -H 'PRIVATE-TOKEN: TN42eT8KyzNs4zKmwDeo' -X POST http://172.16.1.41:10080/api/v4/projects/905/pipeline?ref=master"
    - fi
  artifacts:
    expire_in: 6 mos
    paths:
      - dist
  only:
    - master
    - dev
  tags:
    - k8s

oem:
  stage: build
  script:
    - echo "build-prod started on ref" $CI_COMMIT_REF_NAME
    - cd /managability/warpstor-frontend
    - cp -r /usr/src/app/node_modules /managability/warpstor-frontend/node_modules
    - npm run build:prod
    - OEM_COMPANY=$(echo $CI_COMMIT_REF_NAME | cut -d'/' -f 2)
    - echo "start replace oem assets for" $OEM_COMPANY
    - ./scripts/runwarpstorOem.sh $OEM_COMPANY dist/assets/
  artifacts:
    paths:
      - dist
  only:
    - /^oem\/.+/
  tags:
    - k8s
